language: java
jdk: oraclejdk11

# https://github.com/travis-ci/travis-ci/issues/6298#issuecomment-234091797
# git strips the wrapper jar file so we have to force its download during the build 
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
